Description: AWS role to manage DI Self-Service infrastructure from GitHub Actions
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  GitHubOrg:
    Type: String
    Default: alphagov
  RepositoryName:
    Type: String
    Default: di-onboarding-self-service-experience
  OIDCProviderArn:
    Description: ARN of the the GitHub OIDC provider
    Type: String
  AppName:
    Type: String
    Default: self-service
  InfrastructureStack:
    Description: Name of the self-service infrastructure SAM stack
    Type: String
    Default: sse-infrastructure

Resources:
  GitHubRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref OIDCProviderArn
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*
      Policies:
        - PolicyName: GitHubActions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - ecr:GetAuthorizationToken
                  - ecs:ListTaskDefinitions
                  - ecs:DescribeTaskDefinition
                  - ecs:RegisterTaskDefinition
                  - ecs:DeregisterTaskDefinition

              - Effect: Allow
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/${InfrastructureStack}*
                Action: iam:PassRole

              - Effect: Allow
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/*
                Action: ssm:GetParameter

              - Effect: Allow
                Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${AppName}/*
                Action:
                  - ecr:InitiateLayerUpload
                  - ecr:CompleteLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:BatchCheckLayerAvailability
                  - ecr:BatchDeleteImage
                  - ecr:DescribeImages
                  - ecr:BatchGetImage
                  - ecr:ListImages
                  - ecr:PutImage

Outputs:
  GitHubRoleARN:
    Value: !GetAtt GitHubRole.Arn
