name: Build frontend app

on: workflow_call
permissions: read-all

concurrency:
  group: build-front-app-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Self-service front
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: express }

    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install Node dependencies
        run: npm install --include-workspace-root

      - name: Build app
        run: npm run build

      - name: Archive distribution artifact
        uses: actions/upload-artifact@v3
        with:
          name: self-service-front
          retention-days: 7
          path: |
            express/dist
            express/stubs
            express/resources
            express/src/views
            express/assets/images
            express/manifest.yml
            express/package*.json
            package*.json
