name: Build frontend image

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }
    secrets:
      aws-role-arn: { required: true }

concurrency:
  group: build-front-image-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Frontend image
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: alphagov/di-github-actions/aws/ecr/build-docker-image@6313465e0c640aff9e5f7631dc1e6f70d253dce2
        with:
          aws-role-arn: ${{ secrets.aws-role-arn }}
          repository: self-service/frontend
          image-version: ${{ github.sha }}
          image-tags: ${{ github.head_ref || github.ref_name }}
          build-path: express
