name: Delete deployment

on:
  workflow_dispatch:
  schedule:
    # Every weekday at 10am
    - cron: '0 10 * * 1-5'
  pull_request:
    types: [ closed ]

concurrency:
  group: deploy-${{ github.head_ref || github.ref_name }}

jobs:
  delete-paas-deployment:
    name: Delete app preview
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: PaaS login
        uses: alphagov/di-github-actions/paas/log-in-to-paas@e0e43b4ca78aca47971596806a8f4693e6a84dc7
        with:
          cf-org-name: gds-digital-identity-onboarding
          cf-space-name: self-service-preview
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}

      - name: Get app name
        if: ${{ github.event_name != 'schedule' }}
        uses: alphagov/di-github-actions/beautify-branch-name@e0e43b4ca78aca47971596806a8f4693e6a84dc7
        with:
          downcase: true
          length-limit: 63
          underscores-to-hyphens: true
          prefix: di-sse-prev
          set-env-var: APP_NAME
          usage: App name

      - name: Delete app
        if: ${{ github.event_name != 'schedule' }}
        run: cf delete "$APP_NAME" -rf

      - name: Clean up stale deployments
        if: ${{ github.event_name == 'schedule' }}
        uses: alphagov/di-github-actions/paas/delete-stale-apps@e0e43b4ca78aca47971596806a8f4693e6a84dc7
        with:
          age-threshold-days: 30

  delete-fargate-deployment:
    name: Delete Fargate deployment
    runs-on: ubuntu-latest
    environment: development
    if: ${{ github.event_name == 'schedule' }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.GHA_AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Clean up stale task definitions
        uses: alphagov/di-github-actions/aws/ecs/deregister-stale-task-definitions@e0e43b4ca78aca47971596806a8f4693e6a84dc7
        with:
          family: self-service-frontend
          container: self-service-frontend
