name: Delete deployment

on:
  workflow_dispatch:
  schedule:
    # Every weekday at 10am
    - cron: '0 10 * * 1-5'
  pull_request:
    types: [ closed ]

permissions: read-all

jobs:
  delete-paas-deployment:
    name: Delete app preview
    runs-on: ubuntu-latest
    environment: preview
    concurrency: deploy-paas-${{ github.head_ref || github.ref_name }}
    steps:
      - name: PaaS login
        uses: alphagov/di-github-actions/paas/log-in-to-paas@0296e8125a9293d4dfd393ebc83785147f5f5927
        with:
          cf-org-name: gds-digital-identity-onboarding
          cf-space-name: self-service-preview
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}

      - name: Get app name
        if: ${{ github.event_name != 'schedule' }}
        uses: alphagov/di-github-actions/beautify-branch-name@0296e8125a9293d4dfd393ebc83785147f5f5927
        with:
          downcase: true
          length-limit: 63
          underscores-to-hyphens: true
          prefix: di-sse-prev
          set-env-var: APP_NAME
          usage: App name

      - name: Delete app
        if: ${{ github.event_name != 'schedule' }}
        run: cf delete "$APP_NAME" -rf

      - name: Clean up stale deployments
        if: ${{ github.event_name == 'schedule' }}
        uses: alphagov/di-github-actions/paas/delete-stale-apps@0296e8125a9293d4dfd393ebc83785147f5f5927
        with:
          age-threshold-days: 30

  delete-fargate-deployment:
    name: Delete Fargate deployment
    runs-on: ubuntu-latest
    environment: development
    concurrency: deploy-fargate-${{ github.head_ref || github.ref_name }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Delete docker image
        if: ${{ github.event_name != 'schedule' }}
        uses: alphagov/di-github-actions/aws/ecr/delete-docker-images@0296e8125a9293d4dfd393ebc83785147f5f5927
        with:
          aws-role-arn: ${{ secrets.GHA_AWS_ROLE_ARN }}
          repository: self-service/frontend
          image-tags: ${{ github.head_ref || github.ref_name }}

      - name: Clean up stale task definitions
        if: ${{ github.event_name == 'schedule' }}
        uses: alphagov/di-github-actions/aws/ecs/deregister-stale-task-definitions@0296e8125a9293d4dfd393ebc83785147f5f5927
        with:
          aws-role-arn: ${{ secrets.GHA_AWS_ROLE_ARN }}
          family: self-service-frontend
          container: self-service-frontend
