name: Deploy branch

on: workflow_dispatch

jobs:
  build:
    name: Build
    uses: alphagov/di-onboarding-self-service-experience/.github/workflows/build.yml@7db9076ab867598429c189e883a46cba1c709405

  deploy-preview:
    name: Preview
    needs: build
    uses: alphagov/di-onboarding-self-service-experience/.github/workflows/deploy-to-paas.yml@6886388b7ead03aca510128b30d5053a1693502e
    with:
      environment: preview
      cf_space_name: self-service-mvp
      app_name: di-sse-prev-${{ github.ref_name }}
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
