name: Deploy branch 
run-name: Deploy preview [${{ github.head_ref || github.ref_name }}]

on: workflow_dispatch
permissions: read-all

jobs:
  build-front-app:
    name: Build
    uses: ./.github/workflows/build-front-app.yml

  deploy-front-app:
    name: Preview
    needs: build-front-app
    uses: ./.github/workflows/deploy-to-fargate.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: development
    secrets:
      aws-role-arn: ${{ secrets.ABDUL_GHA_ROLE_ARN }}
      ecs-task-role-arn: ${{ secrets.ABDUL_GHA_ROLE_ARN }}
      ecs-execution-role-arn: ${{ secrets.ABDUL_GHA_ROLE_ARN }}
