name: Push Docker Image to ECR

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }
    secrets:
      aws-role-arn: { required: true }
      ecs-task-role-arn: { required: false }
      ecs-execution-role-arn: { required: false }

concurrency: deploy-fargate-${{ inputs.environment }}-${{ github.head_ref || github.ref_name }}

permissions:
  id-token: write
  contents: read

jobs:
  pushImage:
    name: Push to ECR
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.aws-role-arn }}
          aws-region: eu-west-2

      - name: Push Docker image
        id: push-docker-image
        uses: alphagov/di-github-actions/aws/ecr/build-docker-image@57518aaab7352ff25b417b61016e3063cbdd19d4
        with:
          repository: container-image-repository-containerrepository-2n61fxouradf
          image-version: ${{ github.sha }}
          image-tags: ${{ github.head_ref || github.ref_name }}
          build-path: express
