name: Acceptance tests

on:
  workflow_call:
    inputs:
      host: { required: true, type: string }

permissions: read-all
concurrency: deploy-paas-${{ github.head_ref || github.ref_name }}

jobs:
  run-acceptance-tests:
    name: Acceptance
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: express }

    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Install Node dependencies
        run: npm install

      - name: Run cucumber tests
        env:
          HOST: ${{ inputs.host }}
        run: npm run cucumber
